#!/usr/bin/env bash
# Configure Nginx so that its HTTP
#
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 26071-web-01 44.210.150.159:80 check
    server 26071-web-02 35.173.47.15:80 check
"
# Updating packages
apt-get -y update
apt-get -y upgrade

# Adding HAProxy PPA
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

# Installing HAProxy
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
